name: Build User Service Image
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  AWS_REGION: us-east-1
  SERVICE: users

permissions:
  contents: read
  id-token: write

jobs:
  docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActions_mesh_labs
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Set Image Tag
        id: image
        run: |
          IMAGE_NAME="${{ steps.login-ecr.outputs.registry }}/${{ env.SERVICE }}-service"
          DATE_TAG=$(date +'%Y%m%d')
          GIT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)

          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            TAG_PREFIX="pr-${{ github.event.pull_request.number }}"
          else
            BRANCH_NAME="${{ github.ref_name }}"
            TAG_PREFIX="${BRANCH_NAME//\//-}"
          fi

          IMAGE_TAG="${TAG_PREFIX}-${DATE_TAG}-${GIT_SHA}"

          echo "image_name=${IMAGE_NAME}" >> $GITHUB_OUTPUT
          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
          echo "full_image=${IMAGE_NAME}:${IMAGE_TAG}" >> $GITHUB_OUTPUT

          echo "ðŸ“¦ Image: ${IMAGE_NAME}:${IMAGE_TAG}"

      - name: Build and Push image
        uses: docker/build-push-action@v6
        with:
          context: ./app/users
          provenance: false
          sbom: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: ${{ steps.image.outputs.full_image }}
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

